import os
from flask import Flask, request, render_template

app = Flask(__name__)

hospital_data = [
    {"name": "Sterling Hospitals-Memnagar","address": "Sterling Hospital RD, near Maharaja Agrasen Vidhyalaya, L.K Society, Nilmani Society, Memnagar, Ahmedabad, Gujarat 380052","phone": "09898987878","city":"Ahmedabad"},
    {"name": "Narayana Hospitals","address": "Police Station, Cross Rd, nr. Chakudiya Mahadev Road, opp. Rakhial, Rakhial, Ahmedabad, Gujarat 380023","phone": "08067506878","city":"Ahmedabad"},
    {"name": "Aartham Multi Super Speciality Hospital","address": "Dr Vikram Sarabhai Marg, near Panjrapole Cross Road, L Colony, Ambawadi, Ahmedabad, Gujarat 380015","phone": "07926306401","city":"Ahmedabad"},
    {"name": "Apollo Hospitals City Centre","address": "Tulsi Baugh Society,No.1, Apollo Hospital Ln, near Parimal Garden, Opposite Doctor House, Ambawadi, Ahmedabad, Gujarat 380006","phone": "07966305800","city":"Ahmedabad"},
    {"name": "Shalby Multi-Specialty Hospitals","address": "Sarkhej - Gandhinagar Hwy, opp. Karnavati Club, Ramdev Nagar, Ahmedabad, Gujarat 380015","phone": "07940203000","city":"Ahmedabad"},
    {"name": "Aarna Hospital","address": "Suvidha Shopping Center, Chimanlal Girdharlal Rd, Paldi, Ahmedabad, Gujarat 380007","phone":"07940108108","city":"Ahmedabad"},
    {"name": "SVP Hospital","address": "Ellisbridge, Ahmedabad, Gujarat 380006","phone":"07926436666","city":"Ahmedabad"},
    {"name": "Nidhi Multispeciality Hospital","address": "Shree Kunj Building Stadium Commerce College Road, Commerce Six Rd, Nr Azad Sweets, Navrangpura, Ahmedabad, Gujarat 380009","phone":" 07940232121","city":"Ahmedabad"},
    {"name": "Venus Hospital","address": "City Centre Arcade And Homes Club House, 313-315, Narol - Naroda Rd, near SRP ground, Krishna Nagar, Naroda, Ahmedabad, Gujarat 382345","phone":"09974724724","city":"Ahmedabad"},
    {"name": "Mahavir Hospital","address": "101, Mahavir Status, Virat Nagar Rd, near Manmohan, Nikol, Ahmedabad, Gujarat 382350","phone":" 09624365700","city":"Ahmedabad"},
    
    {"name": "Shalby Multi-Specialty Hospitals","address": "Nr. Navyug College, Rander Rd, Adajan, Surat, Gujarat 395009","phone":"02617190000","city":"Surat"},
    {"name": "Kiran Multi Super Speciality Hospital","address": "Vasta Devdi Road, near Sumul Dairy Road, Katargam, Surat, Gujarat 395004","phone":"02617161111","city":"Surat"},
    {"name": "SURAT MULTISPECIALITY HOSPITAL & ICU & TRAUMA CENTER","address": "Shree Darshan Complex, Station Rd, opp. L D SCHOOL, Opp. LD High School, Raj Nagar, Sachin, Surat, Gujarat 394230","phone":"....","city":"Surat"},
    {"name": "Unique Hospital","address": "Civil Hospital-Char Rasta Sosyo Circle, Vesu Canal Rd, opp. Kiran Motor, Surat, Gujarat 395002","phone":"02612636318","city":"Surat"},
    {"name": "Nirmal Hospital Pvt Ltd","address": "Nirmal Hospital, Sagrampura, Surat, Gujarat 395002","phone":"02614089999","city":"Surat"},
    {"name": "SIMS Hospital","address": "Katargam Rd, near Modh Vanik Vadi, near Railway Station, Vijaya Nagar-1, Lal Darwaja, Rughnathpura, Surat, Gujarat 395003","phone":"02612430000","city":"Surat"},
    {"name": "Asutosh Hospital","address": "Rajashri Hall Road, beside Kshetrapal Hanuman Temple, Majura Gate, Surat, Gujarat 395002","phone":"09374476310","city":"Surat"},
    {"name": "Sita Hospital - ORTHOPAEDIC SUPERSPECIALITY","address": "J.M.Doctor House, Behind JK Tower, Old Sub Jail, Ring Road, GIDC, Khatodra Wadi, Surat, Gujarat 395002","phone":"02612632100","city":"Surat"},
    {"name": "LifeLine Multispeciality Hospital","address": "Shreenathji Complex, 1st, Rander Rd, Ramnagar Char Rasta, Surat, Gujarat 395009","phone":"09099733366","city":"Surat"},
    {"name": "Saurabh Hospital","address": "3rd & 4th Floor, Veerbhardra Building Opposite SVNIT College, Besides IOC Petrol Pump Ichhanath, Dumas Rd, Parle Point, Surat, Gujarat 395007","phone":"09825198103","city":"Surat"},

    {"name": "Sterling Hospitals","address": "Circle West, Race Course Road Opposite Inox Cinema, Hari Nagar, Vadodara, Gujarat 390007","phone":"07573977773","city":"Vadodara"},
    {"name": "Baroda Hospital","address": "Anant Apartment, 1st Floor, Tilak Rd, beside Aradhana Cinema, Salatwada, Vadodara, Gujarat 390001","phone":"02652429262","city":"Vadodara"},
    {"name": "Aadicura Superspeciality Hospital","address": "Jetalpur Rd, behind Gujarat Kidney Hospital, Anand Nagar, Haripura, Vadodara, Gujarat 390020","phone":"08980557711","city":"Vadodara"},
    {"name": "Bhailal Amin General Hospital","address": "Bhailal Amin Marg, Gorwa, Vadodara, Gujarat 390003","phone":"08069707070","city":"Vadodara"},
    {"name": "Sangam Hospital - Multispeciality Hospital/Trauma Centre","address": "Sangam Char Rasta, Saikrupa society, Karelibagh, Vadodara, Gujarat 390022","phone":"09925240395","city":"Vadodara"},
    {"name": "Janvi Multispeciality Hospital","address": "302, Silver Square Complex, Airport Rd, near Gada Circle, Vadodara, Gujarat 390022","phone":"09978989288","city":"Vadodara"},
    {"name": "Metro Hospital & Research Institute","address": "Sama - Harni Rd, beside Kendriya Vidhyalaya, Shivam Park Society, BSNL Colony, Karelibagh, Vadodara, Gujarat 390022","phone":"09601277020","city":"Vadodara"},
    {"name": "Aman Hospital & Research Center - Best ICU With Ventilators | Physician in Gotri Vadodara","address": "15 Shaswat, Gotri Rd, opposite ESI Hospital, Vadodara, Gujarat 390021","phone":"09904402122","city":"Vadodara"},
    {"name": "Tricolour Hospitals - Multispeciality Hospital","address": "Dr. Vikram Sarabhai Road, Genda Cir, Vadiwadi, Vadodara, Gujarat 390007","phone":"02652477777","city":"Vadodara"},
    {"name": "Balaji Hospital","address": "Ellora Park Rd, opposite Vidya Vikas School, Ellora Park, Subhanpura, Vadodara, Gujarat 390023","phone":"07621824538","city":"Vadodara"},

    {"name": "N.M. Virani Wockhardt Hospital","address": "Kalawad Road Near St. Mary's High School, Rajkot, Gujarat 360007","phone":"09512007149","city":"Rajkot"},
    {"name": "Christ Hospital","address": "Jamnagar Rd, opp. Kesar Agency, Madhapar, Rajkot, Gujarat 360006","phone":"08000003336","city":"Rajkot"},
    {"name": "Genesis Multispeciality Hospital","address": "Chandan Park Main Road, Raiya Rd, Nr. Paradise hall, Indian Park, Rajkot, Gujarat 360007","phone":"07574000508","city":"Rajkot"},
    {"name": "Sterling Hospitals","address": "Plot No.251, Police Station, 150 Feet Ring Rd, opp. Gandhigram, Dharam Nagar, Rajkot, Gujarat 360007","phone":"02816785600","city":"Rajkot"},
    {"name": "Sadbhavna MultiSpeciality Hospital","address": "150 Feet Ring Rd, Gandhigram, Rajkot, Gujarat 360007","phone":"09512310108","city":"Rajkot"},
    {"name": "Kadivar Multispeciality Hospital","address": "Jamnagar Rd, near Madhapar Chowkdi, Gayatridham Society, Press Colony, Puneet Nagar, Bajrang Wadi, Rajkot, Gujarat 360006","phone":"09879826156","city":"Rajkot"},
    {"name": "Milestone Hospital","address": "Vidya Nagar Main Rd, near Virani Chowk, Virani Chowk, Bhakti Nagar, Rajkot, Gujarat 360001","phone":"....","city":"Rajkot"},
    {"name": "HCG Hospitals","address": "HCG Hospital Road, Ayodhya Chowk, Off, 150 Feet Ring Rd, nr. Aastha Avenue, Rajkot, Gujarat 360006","phone":"06358888817","city":"Rajkot"},
    {"name": "Sahyog Hospital Pvt. Ltd.","address": "Mavdi Main Road, opp. Vishveshwar Mahadev Temple, Uday Nagar, Rajkot, Gujarat 360004","phone":"02812360343","city":"Rajkot"},
    {"name": "Saarthi hospital","address": "Shiv ratna complex, vidhyanagar, Balaji Park Main Rd, opp. milestone hospital, Rajkot, Gujarat 360002","phone":"07777926688","city":"Rajkot"},

    {"name": "HCG Hospitals","address": "1139 Sir Patini Road, Meghani Cir, Krishna Nagar, Bhavnagar, Gujarat 364001","phone":"06358888816","city":"Bhavnagar"},
    {"name": "BIMS Multispeciality Hospital","address": "Jail Rd, opp. Sir T Hospital, Panwadi, Bhavnagar, Gujarat 364001","phone":"02786644444","city":"Bhavnagar"},
    {"name": "Sir Takhtasinhji General Hospital","address": "Jail Rd, Kalanala, Panwadi, Bhavnagar, Gujarat 364002","phone":"02782423250","city":"Bhavnagar"},
    {"name": "Pulse Plus Multi Speciality Hospital","address": "Gopal Arcade, Near Top-3 Circle Adhewada, Talaja Rd, Bhavnagar, Gujarat 364002","phone":"06359599090","city":"Bhavnagar"},
    {"name": "Jivandeep Hospital Bhavnagar","address": "Jewels Cir, Vijayrajnagar, Bhavnagar, Gujarat 364002","phone":"02782525100","city":"Bhavnagar"},
    {"name": "Nirmal Hospital Bhavnagar","address": "Waghawadi Rd., nr. Parag Travels, opp. Madhav Hill, Pragati Nagar, Takhteshwar Plots, Bhavnagar, Gujarat 364002","phone":"02782221206","city":"Bhavnagar"},
    {"name": "Vivekanand Multispeciality Hospital","address": "Ground Floor, ASHTAVINAYAK CITY MALL, Waghawadi Rd., opp. madhavdarshan, Nanbhawadi, Takhteshwar Plots, Bhavnagar, Gujarat 364002","phone":"09081218386","city":"Bhavnagar"},
    {"name": "Sadvichar General Hospital","address": "Shree alekh complex, 2nd and 3rd floor,Leela circle, Bhavnagar - Sidsar Rd, Bhavnagar, Gujarat 364002","phone":"09825515757","city":"Bhavnagar"},
    {"name": "Soul HealthCare","address": "Kalubha Rd, opp. Madhav Deep Complex, Kalanala, Panwadi, Bhavnagar, Gujarat 364002","phone":"09073989898","city":"Bhavnagar"},
    {"name": "Shantilal Shah Hospital","address": "847 A/1, Diamond Chowk, Mahila College Area, Tilak Nagar, Bhavnagar, Gujarat 364001","phone":"02782206151","city":"Bhavnagar"},

    {"name": "Samarpan General Hospital","address": "Airport Rd, Ajanta Society, Jamnagar, Gujarat 361006","phone":"02882712728","city":"Jamnagar"},
    {"name": "Guru Gobindsingh Government Hospital","address": "G G Hospital, Pandit Nehru Marg, Jamnagar, Gujarat 361008","phone":"....","city":"Jamnagar"},
    {"name": "Shraddha Hospital","address": "Sumair Club Road, behind Axis Bank, Jamnagar, Gujarat 361005","phone":"02882670000","city":"Jamnagar"},
    {"name": "Sharda Hospitals","address": "F385+XF3 Bus Stand, Summair Club Rd, opposite S T, Summair Club Road, Jamnagar, Gujarat 361005","phone":"02882563737","city":"Jamnagar"},
    {"name": "Siddhi Vinayak & Children Hospital","address": "Pandit Nehru Marg, opp. INCOME TAX OFFICE, behind K D Jewelers, Valkeshwari, Park Colony, Jamnagar, Gujarat 361008","phone":"02882510077","city":"Jamnagar"},
    {"name": "Jamnagar Critical Care Hospital","address": "F376+6VR, Oshwal Colony, Summair Club Road, Jamnagar, Gujarat 361005","phone":"02882563056","city":"Jamnagar"},
    {"name": "Gokul Newtech Hospital","address": "NAGARI SAMAY TRAVELS, PLOT NO 97, opp. JAMNAGAR, Valkeshwari, Gujarat 361005","phone":"09099966915","city":"Jamnagar"},
    {"name": "Jeevandhara Hospital","address": "Street No. 2, Oshwal Colony, Summair Club Road, Jamnagar, Gujarat 361005","phone":"02882568166","city":"Jamnagar"},
    {"name": "Madhav Hospital","address": "Summer Club Road, Opp. S T Depot, Kailash Nagar, Jamnagar, Gujarat 361005","phone":"02882566782","city":"Jamnagar"},
    {"name": "Dwarkashish Hospital","address": "Muralidhar Complex, Jakat naka, Gokulnagar Main Rd, above Ashaura Hotel, Gokul Nagar, Jamnagar, Gujarat 361004","phone":"09512515814","city":"Jamnagar"},
    
    {"name": "Radhe Multispecialty Hospital","address": "B राधे सिग्नेचर BLOCK-AB, Palm Rd, opposite सहजानंद सिटी, Urjanagar 1, Kudasan, Gandhinagar, Gujarat 382421","phone":"07923600410","city":"Gandhinagar"},
    {"name": "GMERS Gandhinagar Civil Hospital","address": "951, Rd Number 3, Sector 12B, Gandhinagar, Gujarat 382007","phone":"07923240296","city":"Gandhinagar"},
    {"name": "Aashka Multispeciality Hospital","address": "Gandhinagar Bypass Rd, Sargasan, Gandhinagar, Gujarat 382421","phone":"07575006000","city":"Gandhinagar"},
    {"name": "Hi-Tech Hospital","address": "1186, GH Rd, Sector 3D, Sector 3, Gandhinagar, Gujarat 382016","phone":"07923240555","city":"Gandhinagar"},
    {"name": "Sharda Hospital","address": "6J8R+38Q, Zaverchand Meghani Cir, Sector 7, Gandhinagar, Gujarat 382007","phone":"07923220828","city":"Gandhinagar"},
    {"name": "Anand Multispeciality Hospital","address": "4th Floor Sarthak Mall, Mahatma Mandir Road, Cross Road, Sargasan, Gandhinagar, Gujarat 382421","phone":"09824017400","city":"Gandhinagar"},
    {"name": "Sanjeevani Hospital","address": "Plot No.149, CHH Rd, Sector 21, Gandhinagar, Gujarat 382021","phone":"07923241074","city":"Gandhinagar"},
    {"name": "Divine Multispeciality Hospital","address": "2nd and 3rd floor SHIKSHAPATRI sky court, Swagat Flamingo Rd, Sargasan, Gandhinagar, Gujarat 382421","phone":"07861812967","city":"Gandhinagar"},
    {"name": "Surmount Multi Speciality Hospital","address": "Plot No: R16, behind D-Mart, Green City, Sector 26, Gandhinagar, Gujarat 382421","phone":"08469880550","city":"Gandhinagar"},
    {"name": "Jalaram Hospital","address": "Plot No 1523 GH Road, gh-2, near apna Bazar, Sector 6, Gandhinagar, Gujarat 382006","phone":"09601811611","city":"Gandhinagar"},

    {"name":"Shraddha Hospital","address": "Mahavir Rd, near Pioneer High School, Patel Colony, Sardar Ganj, Anand, Gujarat 388001","phone":"09825245108","city":"Anand"},
    {"name":"Anand Orthopedic Hospital","address": "Near Over Bridge, Bhalej Rd, Beside Bagiwala, Anand, Gujarat 388001","phone":"02692267321","city":"Anand"},
    {"name":"Zydus Hospitals","address": "Anand-Lambhvel Road, Zydus Rd, Anand, Gujarat 388001","phone":"02692619501","city":"Anand"},
    {"name":"Anand Laparoscopy Centre & Hospital","address": "100 Feet Rd, near Himalaya Retreat, Priyadarshini Society, Anand, Gujarat 388001","phone":"....","city":"Anand"},
    {"name":"General Hospital Anand","address": "HX58+43M, Mahatma Gandhi Rd, Ganesh Chokdi, Sardar Ganj, Anand, Gujarat 388001","phone":"....","city":"Anand"},
    {"name":"Anand Homeopathic Hospital","address": "Opp. Sardar baug, Nr. New Bus stand, Anand, Gujarat, Anand, Gujarat 388001","phone":"02692254151","city":"Anand"},
    {"name":"Shashwat Hospital & I.C.U.","address": "17, 100 Feet Rd, Nanikhodiyar, Anand, Gujarat 388001","phone":"08980526000","city":"Anand"},
    {"name":"Sankalp Hospital","address": " 1ST FLOOR, SUN HOUSE BUILDING, Gujarat 388001","phone":"09898781373","city":"Anand"},
    {"name":"IRIS Hospital","address": "Lambhvel Rd, Patel Chokdi, Purushottam Nagar, Anand, Gujarat 388120","phone":"02692288200","city":"Anand"},
    {"name":"Chaitanya Hospital","address": "Deep Circle, Bhalej Rd, opp. Yogim Sankul, nr. New Bus Station, Anand, Gujarat 388001","phone":"02692257878","city":"Anand"},

    {"name": "Anand Orthopaedic Hospital","address": "DP Desai Rd, Nadiad, Gujarat 387001","phone": "....","city":"Nadiad"},
    {"name": "Keya Hospitals","address": "Near Patel society, Nadiad, Gujarat 387002","phone":"090330 31132","city":"Nadiad"},
    {"name": "Shubham Hospital","address": "VKV Rd, behind Santram Eye Hospital, Gitanjali Nagar Society, Shanti Nagar, Nadiad, Gujarat 387001","phone":"....","city":"Nadiad"},
    {"name": "Shlok Multispeciality Hospital","address": "Opp Shri Mai Mandir, Mai Mandir Rd, Nadiad, Gujarat 387002","phone":"0268 255 9108","city":"Nadiad"},
    {"name": "Tulsi Hospital","address": "MVV6+4JH, Pij Bhagole Rd, Ghodia Bazar, Junaraopura, Nadiad, Gujarat 387001","phone":"....","city":"Nadiad"},
    {"name": "Dr. B L Bhatt Hospital","address": "Dabhan Bhagole, Junaraopura, Nadiad, Gujarat 387001","phone":"0268 256 6097","city":"Nadiad"},
    {"name": "Krutarth Hospital","address": "MVR8+RCC, Globe Cinema Road, Desai Vago, Nadiad, Gujarat 387001","phone":"0268 256 6001","city":"Nadiad"},
    {"name": "Dr.Vikram Hospital","address": "S/1, 2ND FLOOR, SKYLINE, College Rd, opposite MAHAGUJARAT HOSPITAL, Nadiad, Gujarat 387001","phone":"075678 28686","city":"Nadiad"},
    {"name": "Amee Multispeciality Hospital","address": "Prime Centre, Besides, Desai Vago, Nadiad, Gujarat 387001","phone":"081540 27444","city":"Nadiad"},
    {"name": "Rudra Hospital","address": "Santram Society Rd, Shanti Nagar, Nadiad, Gujarat 387001","phone":"....","city":"Nadiad"},

    {"name":"Viable Multispeciality Hospital", "address":"1st Floor, Hospital Rd, opp. Ambaji Temple, Vijay Nagar, Bhuj, Gujarat 370001", "phone":"078746 76744", "city":"Bhuj"},
    {"name":"Accord Multi specialist Hospital", "address":"SH 48, Mundra - Bhuj Rd, near SBI ATM, Nirmalsinh Vadi, BSF BN HQ, Bhuj, Gujarat 370001", "phone":"02832 230 033", "city":"Bhuj"},
    {"name":"Shree Sahjanand Hospital", "address":"6MPG+8C4, New Lotus Colony Rd, New Lotus Colony, Madhapar, Bhuj, Gujarat 370001", "phone":"....", "city":"Bhuj"},
    {"name":"G.K.General Hospital", "address":"adani institute of medical science, GAIMS Campus, Bhuj, Gujarat 370001", "phone":"02832 258 071", "city":"Bhuj"},
    {"name":"K.K.Patel Super Speciality Hospital", "address":"Bhuj - Mundra Road, University, nr. Kutch, Bhuj, Gujarat 370001", "phone":"091043 12022", "city":"Bhuj"},
    {"name":"Parmarth Anorectal Hospital", "address":"Neelkanth, Opp. Rajaram Complex, Hospital Rd, Bhuj, Gujarat 370001", "phone":"02832 250 885", "city":"Bhuj"},
    {"name":"Lions Hospital", "address":"6JRV+QXR, Hill Garden Road, Commerce College Rd, Bhuj, Gujarat 370001", "phone":"02832 256 098", "city":"Bhuj"},
    {"name":"Akshar Hospital", "address":"Hospital Rd, above Sahkar Optics, opp. Anjali Tower, Vijay Nagar, Bhuj, Gujarat 370001", "phone":"094292 98871", "city":"Bhuj"},
    {"name":"J.K. Hospital", "address":"6MRC+2R9, Madhapar, Bhuj, Gujarat 370001", "phone":"....", "city":"Bhuj"},
    {"name":"Fusion Multispeciality Hospital", "address":"146,vijaynagar b/h rotary hall near bhuj english school, Hospital Rd, Bhuj, Gujarat 370001", "phone":"02832 258 915", "city":"Bhuj"},
]

lab_data = [
    {"name": "Ahmedabad Laboratories","address": "C-26,Rajratna Shopping Center, Rajendra Park Rd, near R.D.School, Ramrajya Nagar, Odhav, Ahmedabad, Gujarat 382415","phone":"08530290095","city":"Ahmedabad"},
    {"name": "Rushabh Pathology Laboratory","address": "Sahajanand Palace, 100 Feet Road, Opposite Rahul Tower/ Shyamal To Karnawati Club Road, 100 Feet Road, Ahmedabad, Gujarat 380051","phone":"07926932040","city":"Ahmedabad"},
    {"name": "Pragati Laboratory","address": "No.2nd Floor, Shree Ganesh Bhavan, Opposite City mall Compound, Dayanand Rd, Gita Mandir, Ahmedabad, Gujarat 380002","phone":"07925453435","city":"Ahmedabad"},
    {"name": "Gujarat Laboratory","address": "F-16/17,Madhavpura Market, Near Police Commissioner Office, Shahibag, Ahmedabad, Gujarat 380004","phone":"079 2562 6040","city":"Ahmedabad"},
    {"name": "Qline Diagnostics Pathology Laboratory","address": "Shivalik Yash, B - 203, 132 Feet Ring Rd, Near Shashtri nagar BRTS Stand, Vijaynagar, Naranpura, Ahmedabad, Gujarat 380013","phone":"079 4897 9042","city":"Ahmedabad"},
    {"name": "Credence Pathology Laboratory","address": "First floor, Shop No.1, Shukan Apartment, Opp.Shukan Residency, Vandematram Cross Road, New SG Road, Gota, Ahmedabad, Gujarat 382481","phone":"074051 22333","city":"Ahmedabad"},
    {"name": "Sunflower Laboratory","address": "Drive In Rd, nr. Manav Mandir, Opposite Traffic Police helmet, Memnagar, Ahmedabad, Gujarat 380052","phone":"097277 43111","city":"Ahmedabad"},
    {"name": "Aavkar Pathology Laboratory","address": "Shop No.4-5, Avakar Complex, Drive In Rd, opposite Gurukul Road, Sushil Nagar Society, Memnagar, Ahmedabad, Gujarat 380052","phone":"098250 91657","city":"Ahmedabad"},
    {"name": "Ashish Pathology Laboratory","address": "2HHP+2QC, Pir Mohamadshah Mansion, Gheetkanta Char Rasta, Relief Road, Gheekanta, Bhadra, Ahmedabad, Gujarat 380001","phone":"079 2550 8176","city":"Ahmedabad"},
    {"name": "Nirmaan Pathology Laboratory","address": "Ashok Complex,, 101, Sardar Patel Stadium Rd, Sardar Patel Colony, Sundar Nagar, Navrangpura, Ahmedabad, Gujarat 380014","phone":"079 2646 8444","city":"Ahmedabad"},

    {"name": "Heer Clinical Laboratory","address": "1st Floor, National Plaza, Opp Himson Circle, Near Railway Station, Surat, Gujarat 395003","phone":"0261 241 8165","city":"Surat"},
    {"name": "Global Pathology Laboratory","address": "316 Vesu Point, Vesu chaar rasta, Vesu, Surat, Gujarat 395007","phone":"098980 77497","city":"Surat"},
    {"name": "Virkrupa Clinical Laboratory","address": "Anand Deep Flats, Chowki St, near Rampura Petrol Pump, Sayedpura, Surat, Gujarat 395003","phone":"0261 245 0001","city":"Surat"},
    {"name": "BCL Bharat Laboratory","address": "Upper Ground Floor, JK park shopping center besides Amidhara wadi, New Rander Rd, near Choksi Wadi, Surat, Gujarat 395009","phone":"1800 891 2907","city":"Surat"},
    {"name": "Health Care Pathology Laboratory","address": "205, Second Floor, Surat Kamrej Road, Shubham Doctor, Sarthana Jakat Naka, Nana Varachha, Surat, Gujarat 395006","phone":"097273 97879","city":"Surat"},
    {"name": "Bharat Pathology Laboratory","address": "L-19 B, Parle Point Palace, Below Venus Studio, Parle Point Cir, near A.V. Sons, Surat, Gujarat 395007","phone":"098259 17859","city":"Surat"},
    {"name": "Nilkanth Clinical Laboratory","address": "201/202 Rughnathpura Road Anand Chembers, Khansaheb Na dela ni baju ma, Rughnathpura, Surat, Gujarat 395003","phone":"084019 90537","city":"Surat"},
    {"name": "Shrey Pathology & Microbiology Laboratory","address": "213/214, Green Plaza, L P Savani School Circle, Adajan Dn, TP 10 Main Rd, Surat, Gujarat 395009","phone":"098255 20367","city":"Surat"},
    {"name": "Yashfeen Clinical Laboratory","address": "Shop no 5,sahin complex,Rani talao Rani talao, Main Road, Lal Gate, Surat, Gujarat 395003","phone":"098793 97301","city":"Surat"},
    {"name": "Malavia Advanced Laboratory","address": "305, shivalik western, Subhash Chandra Bose Marg, above TGB Restaurant, opp. McDonald's, TGB, Adajan Gam, Adajan, Surat, Gujarat 395009","phone":"091375 41374","city":"Surat"},

    {"name": "Grace Laboratory","address": "Silver Coin Apartment, FF - 8, Opp.Bhavans School, Manjalpur, Vadodara, Gujarat 390014","phone":"090169 50768","city":"Vadodara"},
    {"name": "Divine Lab","address": "B-201/202 MANGALKIRTI APT NR. UDUPI RESTAURANT, Fatehgunj, Vadodara, Gujarat 390002","phone":"089800 47410","city":"Vadodara"},
    {"name": "Vadodara Clinical Laboratory","address": "Rudra Point, 1st Floor, Near Parivar Vidyalaya Mahavir Cross Road, Ajwa Rd, Vadodara, Gujarat 390019","phone":"063596 48112","city":"Vadodara"},
    {"name": "Baroda Clinical Laboratory","address": "3, BPC Rd, Near Urmi Char Rasta, Purushottam Nagar, Haripura, Vadodara, Gujarat 390020","phone":"....","city":"Vadodara"},
    {"name": "Pratham Microbiology Laboratory","address": "102, Mangaldhara Complex, 83, Sampatrao Colony, Alkapuri, Behind Ivory Terrace, Alkapuri, Vadodara, Gujarat 390007","phone":"098258 92198","city":"Vadodara"},
    {"name": "24 Hours Pathology Laboratory","address": "G/F-20, Kalpvruksh Complex, Gotri Rd, Near Gotri Medical College, Gotri, Vadodara, Gujarat 390021","phone":"096620 53260","city":"Vadodara"},
    {"name": "Nidhi Laboratory","address": "Devdeep Commercial Centre, 16, 1st Floor, Near, Delux Cross Rd, Bhavanipura Society, Sardar Nagar, Nizampura, Vadodara, Gujarat 390002","phone":"0265 279 1030","city":"Vadodara"},
    {"name": "Yash Laboratory","address": "114, Gajanan Complex, Old Padra Rd, Opp. Tube Company, Sheetal Nagar, Akota, Vadodara, Gujarat 390015","phone":"0265 234 5319","city":"Vadodara"},
    {"name": "Namra Pathology Laboratory","address": "101, Jagannathpuri Complex, New IPCL Rd, Subhanpura, Vadodara, Gujarat 390007","phone":"0265 228 3727","city":"Vadodara"},
    {"name": "Vraj Pathology Laboratory","address": "111, Indraprasth, Uma Char Rasta, Waghodia Road, Vadodara, Gujarat 390019","phone":"0265 251 6818","city":"Vadodara"},

    {"name": "Arpan Pathology Laboratory","address": "150 Feet Ring Rd, near The Co-Operative Bank, Indira Circle, Jala Ram Nagar, Rajkot, Gujarat 360007","phone":"094283 44158","city":"Rajkot"},
    {"name": "Saurashtra laboratory","address": "SUVARNABHUMI COMPLEX, Jivraj Park Main Rd, Rajkot, Gujarat 360004","phone":"089056 54778","city":"Rajkot"},
    {"name": "Devnandan Laboratory","address": "bellow Wings IVF Hospital, Jasal Complex ,Shop -15 (GF), Nanavati chock, 150 Feet Ring Rd, Rajkot, Gujarat 360007","phone":"095580 00955","city":"Rajkot"},
    {"name": "Om Pathology Laboratory","address": "Crystal City Complex, Mama Saheb 50 Feet Road, Kuvadava Rd, near D-Mart, Rajkot, Gujarat 360003","phone":"094296 42000","city":"Rajkot"},
    {"name": "Prime Laboratory","address": "GF ORAFACE HOSPITAL OPP BACKBONE SHOPPING CENTER CHANDRESH NAGAR MAIN ROAD, nr. MAYANI CHOWK, Rajkot, Gujarat 360004","phone":"084609 53500","city":"Rajkot"},
    {"name": "Manglam Pathology Laboratory","address": "2nd Floor, Parishram Plaza, Mangla Main Rd, Near Lodhawad Chowk, Manhar Plot Corner, Vijay Plot, Bhakti Nagar, Rajkot, Gujarat 360002","phone":"0281 246 5885","city":"Rajkot"},
    {"name": "The First Care Laboratory","address": "FF- 9A, Nilkanth Plaza, 1st Floor, Mavdi Main Road, near Swaminarayan Temple Bapa Sitaram Chowk, Rajkot, Gujarat 360004","phone":"095104 28695","city":"Rajkot"},
    {"name": "Mahek Pathology Laboratory","address": "3rd Floor , Mediplex Complex, 4 - Manhar Plot Corner,Vidhyanagar Main Road, Rajkot, Gujarat 360002","phone":"0281 246 5522","city":"Rajkot"},
    {"name": "Life care Laboratory","address": "Fire Bridge, Opposite Parshwa Hospital, Bajrang Chowk, Chandreshnagar Main Rd, near Mavdi, Rajkot, Gujarat 360004","phone":"090990 70684","city":"Rajkot"},
    {"name": "Shree Pathology Laboratory","address": "Balaji Complex, 101, Vidya Nagar Main Rd, Below Aastha children hospital, Rajkot, Gujarat 360001","phone":"0281 246 3500","city":"Rajkot"},

    {"name": "Vision Laboratory","address": "Carlton Square, Kalanala Rd, near Dada Saheb Jain Mandir Road, Complex, Nanbhawadi, Panwadi, Bhavnagar, Gujarat 364001","phone":"0278 222 4143","city":"Bhavnagar"},
    {"name": "Shree Krishna Pathology Laboratory","address": "Shop No G1, Alekh Complex, Bhagavati Circle Rd Virani chowk, Kaliyabid, Bhavnagar, Gujarat 364002","phone":"094295 86171","city":"Bhavnagar"},
    {"name": "Arogya Pathology Laboratory","address": "3, Ground floor, Sai Ganga Complex, Kalubha Rd, near GenX Hotel, Bhavnagar, Gujarat 364002","phone":"....","city":"Bhavnagar"},
    {"name": "Sterling Accuris Diagnostics","address": "112-113, Samved Complex, First Floor, Jail Rd, Bhavnagar, Gujarat 364001","phone":"090541 90189","city":"Bhavnagar"},
    {"name": "Gandhi Laboratory","address": "Gujarat - Bhavnagar - Rajkot Road, G-12,DARSHAN COMPLEX, Vishwakarma Circle, near Das Pendawala, Bhavnagar, 364002","phone":"....","city":"Bhavnagar"},
    {"name": "Dhruv Diagnostic Center","address": "Kalubha Rd, Kalanala, Panwadi, Bhavnagar, Gujarat 364002","phone":"0278 251 9400","city":"Bhavnagar"},
    {"name": "Shree Ram Laboratory","address": "Vijayrajnagar, Bhavnagar, Gujarat 364002","phone":"0278 252 5511","city":"Bhavnagar"},
    {"name": "Shree Ganesh Pathology Laboratory","address": "G-26,swastik arcade,leela circle, B.A.D.A. Vikash Path, Bhavnagar, Gujarat 364002","phone":"....","city":"Bhavnagar"},
    {"name": "Shreeji Laboratory","address": "Shop No.28, Kapilesh Complex, Kumundwadi, Bortalav, Road, Bhavnagar, Gujarat 364001","phone":"070168 85365","city":"Bhavnagar"},
    {"name": "Om Diagnostics","address": "G.23, AYUSH plaza, opp. SIR T. HOSPITAL, Bhavnagar","phone":"....","city":"Bhavnagar"},

    {"name": "Unipath Specialty Laboratory","address": "F395+6FW, C/o Sharda Hospital, opposite S.T bus stand, Summer club Road, Jamnagar, Gujarat 361005","phone":"0288 256 2226","city":"Jamnagar"},
    {"name": "Shree Laboratory","address": "M-19, Ranjitsagar Rd, Nandanvan, Sadhana Colony, Jamnagar, Gujarat 361005","phone":"099254 64348","city":"Jamnagar"},
    {"name": "Tanna Laboratory","address": "103, Cross Road, Jamnagar, Gujarat 361008","phone":"094280 74704","city":"Jamnagar"},
    {"name": "Sterling Accuris Diagnostics Pathology Laboratory","address": "V M Shah Hospital, Summair Club Rd, Summair Club Road, Jamnagar, Gujarat 361005","phone":"070969 44408","city":"Jamnagar"},
    {"name": "Joshi Laboratory","address": "Nanubhai Niketan, 16, opposite Digvijay Plot Police Chowky, Digvijay Plot, Jamnagar, Gujarat 361005","phone":"0288 267 7193","city":"Jamnagar"},
    {"name": "Akshar Laboratory","address": "13, Manmandir Building, Amber Cinema Road, opposite Ahir Boarding, Jamnagar, Gujarat 361001","phone":"0288 266 2133","city":"Jamnagar"},
    {"name": "Vidhi Pathology Lab","address": "Banke Naturals Pvt. Ltd., Manek Center, Pandit Nehru Marg, Indradeep Society, Jamnagar, Gujarat 361008","phone":"0288 255 7676","city":"Jamnagar"},
    {"name": "Shreeji Pathology Laboratory","address": "F385+HWX, Summair Club Road, Jamnagar, Gujarat 361005","phone":"0288 256 7273","city":"Jamnagar"},
    {"name": "Shingala Lab","address": "F395+3GX, Summair Club Road, Jamnagar, Gujarat 361005","phone":"0288 256 3000","city":"Jamnagar"},
    {"name": "Bhagwati Laboratory","address": "Soham plaza, 1, Gokulnagar Main Rd, near Somnath medical, Gokul Nagar, Jamnagar, Gujarat 361004","phone":" 090993 34132","city":"Jamnagar"},

    {"name": "Icon Pathology Laboratory","address": "NIRAMAY MEDICAL HUB, near GH3, behind HP PETROLPUMP, Sector 6, Gandhinagar, Gujarat 382006","phone":"....","city":"Gandhinagar"},
    {"name": "Apex Pathology Laboratory","address": "103, Pramukh Nagar Complex, Sargasan, Gandhinagar, Gujarat 382421","phone":"....","city":"Gandhinagar"},
    {"name": "Aarti Pathology Laboratory","address": "Plot No:790/A, 790/A, Rd Number 6, opposite Maharashtra Bhavan, Sector 21, Gandhinagar, Gujarat 382021","phone":"079 2322 9172","city":"Gandhinagar"},
    {"name": "Krishna Pathology & Microbiology Laboratory","address": "Plot No. 578/1, GH-2 Circle, GH Rd, Sector 7G, Sector 7, Gandhinagar, Gujarat 380007","phone":"099984 71171","city":"Gandhinagar"},
    {"name": "AccuRight Diagnostics Pathology Laboratory","address": "Opposite Kadi school bus stop, Near GH-6 circle, GH Rd, Sector 22, Gandhinagar, Gujarat 382022","phone":"075750 35350","city":"Gandhinagar"},
    {"name": "Sharda Pathology Laboratory","address": "Plot No 382, 381, GH Rd, near Trupti Ice-cream Parlour, Sector 16, Gandhinagar, Gujarat 382016","phone":"094997 38611","city":"Gandhinagar"},
    {"name": "Ashirvad Pathology laboratory","address": "E 109/E110 Swagat Rain Forest -1 Opp.Pratik Mall Nr.Black Pepper Restaurant Por, Kudasan Rd, Kudasan, Gandhinagar, Gujarat 382421","phone":"099793 46515","city":"Gandhinagar"},
    {"name": "Micro pathology Laboratory","address": "Shop, no.11,sahjanand status, Pramukhnagar Rd, opp. Pramukh osis, Sargasan, Gandhinagar, Gujarat 382421","phone":"089809 40006","city":"Gandhinagar"},
    {"name": "Radhe Laboratory","address": "306, Akshardeep Complex, Gh-6 corner, Sector 29, Gandhinagar, Gujarat","phone":"....","city":"Gandhinagar"},
    {"name": "SAFELab Diagnostics","address": "FF-128, Shree Rang Plaza 95 GIFT City, Road, Randesan, Gandhinagar, Gujarat 382421","phone":"082779 96697","city":"Gandhinagar"},

    {"name": "Unipath Specialty Laboratory","address": "Ground floor, Vande Mataram Complex, Mayfair Road, near Anand Mercantile Bank, opp. Pioneer school, Patel Colony, Anand, Gujarat 388001","phone":"....","city":"Anand"},
    {"name": "Life Line Laboratory","address": "first floor, Shreeji Arcade, 8, 100 Feet Rd, near indira statue, near Shashwat Hospital, Anand, Gujarat 388001","phone":"082388 99552","city":"Anand"},
    {"name": "Darpan Laboratory","address": "62/63, Shubhlaxmi Shopping Centre, Railway Station Rd, behind Dr. Ajay Kothiala’s Hospital, Anand, Gujarat 388001","phone":"02692 241 602","city":"Anand"},
    {"name": "Anand Pathology Laboratory","address": "VENDOR CROSS ROAD, AHINSA CHOWK, 1ST FLOOR , MANI COMPLEX, NR LAXMI TALKIES, Anand, Gujarat 388001","phone":"02692 269 769","city":"Anand"},
    {"name": "Dr Sanjay Laboratory","address": "Dr Cook Rd, Nandanvan Society, Popati Nagar, Anand, Gujarat 388001","phone":"02692 266 124","city":"Anand"},
    {"name": "Care Pathology Laboratory","address": "Mangalpura B/H Ganesh crossing, IRMA Rd, Anand, Gujarat 388001","phone":"090995 05108","city":"Anand"},
    {"name": "Suyog Clinical Laboratory","address": "Near Charotar Bank, Opp: Gaytry Khanan House, Subhash Road, Railway Station Rd, Anand, Gujarat 388001","phone":"098251 70749","city":"Anand"},
    {"name": "Santram laboratory","address": "8 , jafuda complex balita kaka road Opp bhathiji mandir, Railway Station Rd, Anand, Gujarat 388001","phone":"099793 00329","city":"Anand"},
    {"name": "Vishal Laboratory","address": "HW4H+7WG, Nana Bazaar, Vallabh Vidyanagar, Anand, Gujarat 388120","phone":"092278 75704","city":"Anand"},
    {"name": "Krunal Pathology laboratory","address": "101/102- Shreenathaji complex, Vendor cross, road, Anand, 388001","phone":"02692 269 832","city":"Anand"},

    {"name": "Unitech Laboratory","address": "Near Chandan Medical Store, opp. G.K.General Hospital, Bhuj, Gujarat 370001","phone":" 02832 220 080","city":"Bhuj"},
    {"name": "Riddhi Laboratory","address": "Nanavati hospital, lane, near jiya hospital, near Navkar X ray, Bhuj, Gujarat 370001","phone":"02832 251 750","city":"Bhuj"},
    {"name": "Tanna Laboratory","address": "6MRF+XF6, Vijay Nagar, Bhuj, Gujarat 370001","phone":"02832 258 147","city":"Bhuj"},
    {"name": "Atul Laboratory","address": "82 HOSPITAL ROAD, Hospital Rd, Vijay Nagar, Bhuj, Gujarat 370001","phone":"02832 250 119","city":"Bhuj"},
    {"name": "Kutch Pathology","address": "Old Dhatia Falia, Bhuj, Gujarat 370001","phone":"02832 225 096","city":"Bhuj"},
    {"name": "Sterling Accuris Diagnostics","address": "2nd floor, Sunrise Complex, Lotus Colony Rd, opp. G.K. General Hospital, Lotus Colony, Bhuj, Gujarat 370001","phone":"02832 227 027","city":"Bhuj"},
    {"name": "Jadeja Laboratory","address": "6MVF+84C, Vijay Nagar, Bhuj, Gujarat 370001","phone":"....","city":"Bhuj"},
    {"name": "Shreeji Pathology Laboratory","address": "7, River Front Complex, near New Bridge, Navavas, Madhapar, Bhuj, Gujarat 370020","phone":"02832 240 767","city":"Bhuj"},
    {"name": "Mepani Pathology Laboratory","address": "6PR4+C54, Ashapura Temple Rd, Mahavir Nagar, Junavas, Madhapar, Bhuj, Gujarat 370020","phone":"099041 35918","city":"Bhuj"},
    {"name": "Lifecare Laboratory","address": "Shop no.1, Plot no. 33/A, Ground Floor, Near, Reliance Mall Rd, Nirmalsinh Vadi, Bhanushalinagar, Bhuj, Gujarat 370001","phone":"091041 82048","city":"Bhuj"},

    {"name": "Blue Cross Clinical Laboratory","address": "Santram Mandir Rd, opp. Santram Tower, Dumral Bazar, Junaraopura, Nadiad, Gujarat 387001","phone":"063911 96716","city":"Nadiad"},
    {"name": "Sterling Accuris Laboratory","address": "1st Floor, Above central bank, near Anjali Hospital, Desai Vago, above Central Bank and BOB, Nadiad, Gujarat 387001","phone":"....","city":"Nadiad"},
    {"name": "Riddhi Pathology Laboratory","address": "Riddhi Pathology Laboratory, Santram Road, Nadiad, Gujarat 387001","phone":"0265 255 2620","city":"Nadiad"},
    {"name": "Life Line","address": "First Floor, Santram Mandir Rd, near Gita Mandir, near Santram Mandir, Gitanjali Nagar Society, Shanti Nagar, Nadiad, Gujarat 387001","phone":"0268 255 2261","city":"Nadiad"},
    {"name": "Jhanvi diagnostics","address": " Dr Jayant Shah hospital, Santram Society Rd, Shanti Nagar, Nadiad, Gujarat 387001","phone":"....","city":"Nadiad"},
    {"name": "Lifeline Pathology Laboratory","address": "MVR7+7JG, near Shree Santram Mandir, Shanti Nagar, Nadiad, Gujarat 38700","phone":" 0268 256 4545","city":"Nadiad"},
    {"name": "Jay Ambe Laboratory","address": "24/1 Geetanjali Society, Opp.Virali Medical, Pij Road, Nadiad, Gujarat 387002","phone":"096015 92322","city":"Nadiad"},
    {"name": "Nadiad diagnostic Laboratory","address": "Shop No. 104 first floor, Krishna Crown Complex, near Nexus-3, Bhakti Nagar, Nadiad, Gujarat 387001","phone":"....","city":"Nadiad"},
    {"name": "Health Laboratory Nadiad","address": "Welcome Plaza, 12 A, Vaishali Cinema Rd, Indira Nagar, Nadiad, Gujarat 387002","phone":"099252 47994","city":"Nadiad"},
    {"name": "Santram Pathology and Radiology Lab","address": "MVQ7+7XQ, Mota Kumbhnath Rd, Yogiraj Society, Nadiad, Gujarat 387001","phone":"....","city":"Nadiad"},

]

medical_data = [
    {"name": "Ahmedabad Medical Center","address": "Vinay Market, Punit Maharaj Rd, opposite Railway Station, Maninagar, Ahmedabad, Gujarat 380008","phone":"079 2533 0366","city":"Ahmedabad"},
    {"name": "Ravani Medical Store","address": "Shop No 8, Shubhlaxmi Complex, Vistar, near Sanghvi High School, opposite Bank Of Baroda, Naranpura, Ahmedabad, Gujarat 380013","phone":"1800 23 5700","city":"Ahmedabad"},
    {"name": "Seth Medical","address": "g-8, nawab plaza, near gujarat agro, royal akber tower, Sarkhej Rd, Ahmedabad, Gujarat 380055","phone":"....","city":"Ahmedabad"},
    {"name": "Khushbu Medical Stores","address": "Police Station, 779/5529/7,G.H.B Tran Maliya, Road, near Shubhlaxmi Flat, Bapunagar, Ahmedabad, Gujarat 380024","phone":"099740 09914","city":"Ahmedabad"},
    {"name": "AGeneric medical store amareivadi","address": "2J2G+V2W, Amraiwadi, Ahmedabad, Gujarat 380026","phone":"....","city":"Ahmedabad"},
    {"name": "Adit Medical Centre","address": "near Das khaman shop, off Income tax, underpass, Navrangpura, Ahmedabad, Gujarat 380014","phone":"098980 73923","city":"Ahmedabad"},
    {"name": "Mehta Medical and Surgical","address": "Nr. V S Hospital, Shop No-16 Mehta 531, Ellisbridge, Ahmedabad, Gujarat 380006","phone":"093281 46483","city":"Ahmedabad"},
    {"name": "Best Medical","address": "1, Gomtipur, near Toppi Mill, Rajpur Hirpur, Gomtipur, Ahmedabad, Gujarat 380021","phone":"063536 27242","city":"Ahmedabad"},
    {"name": "Krishna Medical","address": "Shop No. 4/299/4, pirbhai market, Gujarat 380006","phone":"....","city":"Ahmedabad"},
    {"name": "Medical Store","address": "2G64+5PG, Corporate Rd, Prahlad Nagar, Ahmedabad, Gujarat 380015","phone":"....","city":"Ahmedabad"},

    {"name":"Mahadev Medical", "address":"G-7 CAPITAL HUB, Umra Gam, Surat, Gujarat 394130", "phone":"098252 66556", "city":"Surat"},
    {"name":"P.R. Point Medical", "address":"Sai ashis aap, Sai Samarpan Society, Kashi Nagar, Udhana, Surat, Gujarat 394220", "phone":"....", "city":"Surat"},
    {"name":"Maheshwar Medical Stores", "address":"Varachha Main Rd, near Gurunagar Gate, Vallabhnagar Society, Varachha, Surat, Gujarat 395006", "phone":"0261 256 8156", "city":"Surat"},
    {"name":"Sunrise Medical Store", "address":"G 8 Firdus Tower, near Fazal Tower, Towe, Adajan Patiya, Surat, Gujarat 395009", "phone":"096383 22551", "city":"Surat"},
    {"name":"Someshwar Medical", "address":"Smc shopping laldarwaja, Lal Darwaja Station Rd, Surat, Gujarat 395003", "phone":"....", "city":"Surat"},
    {"name":"Rahat Medical", "address":"SHOP NO.1,INDERPURA, Salabatpura, Surat, Gujarat 395002", "phone":"088660 25342", "city":"Surat"},
    {"name":"District Medical Store", "address":"Shop No 32, Chowk Bazar Rd, Shahpore, Sayedpura, Surat, Gujarat 395003", "phone":"....", "city":"Surat"},
    {"name":"Sarvashanti Pharmacy", "address":"Near, UG-04, Raj point, Sandhyavandan Society, Palanpur Jakatnaka, Surat, Gujarat 395009", "phone":"090815 81581", "city":"Surat"},
    {"name":"Surat Medical Stores", "address":"Lal Gate, Main Road, Lal Gate, opposite Uco Bank, Surat, Gujarat 395003", "phone":"0261 241 8212", "city":"Surat"},
    {"name":"Apollo Pharmacy Adajan Surat", "address":"Mann Complex, 6, Anand Mahal Rd, Opposite Shree Ram Petrol Pump, Adajan, Surat, Gujarat 395009", "phone":"076000 41661", "city":"Surat"},

    {"name":"Lagdiwala Medical Centre", "address":"8622+WW2, Mahajan Ln, Raopura, Mandvi, Vadodara, Gujarat 390001", "phone":"0265 242 4655", "city":"Vadodara"},
    {"name":"Meet Medical & General Store", "address":"75RF+VCM, Pratham Avenue, Akota, Vadodara, Gujarat 390020", "phone":"....", "city":"Vadodara"},
    {"name":"Amarnath Medical", "address":"Shangrila Complex 7, Old Padara Road Radhakrishna Chokdi, Opp. HDFC Bank, Near Akota Garden, Sheetal Nagar, Akota, Vadodara, Gujarat 390020", "phone":"098981 80502", "city":"Vadodara"},
    {"name":"Sarjan Medical", "address":"Sarjan complex, G-12, Pratap Rd, opp. Bank Of Baroda, Dandia Bazar, Jambubet, Vadodara, Gujarat 390001", "phone":"....", "city":"Vadodara"},
    {"name":"Jalaram Medical Store", "address":"GF 7 Shreeji gold, CD TOWER, Laxmipura Rd, opp. sona party plot, Gorwa, Vadodara, Gujarat 390023", "phone":"099798 87220", "city":"Vadodara"},
    {"name":"Pramukh Medical & General Store", "address":"SB/12, Pratham Complex, Makrand Desai Rd,Iscon Temple Rd, Mother School Char Rasta, Gadapura, Diwalipura, Vadodara, Gujarat 390015", "phone":"0265 232 6400", "city":"Vadodara"},
    {"name":"Jyoti Medical", "address":"Sanstha Vasahat, Pratap Road, Raopura, Raopura, Vadodara, Gujarat 390001", "phone":"0265 243 4794", "city":"Vadodara"},
    {"name":"Kanaiya Medical", "address":"85FQ+GGC, Lady Pillar Road, Fatehgunj, Fatehgunj, near Uda Off, Vadodara, Gujarat 390002", "phone":"0265 279 3685", "city":"Vadodara"},
    {"name":"House Secretary Medical Care", "address":"K G Patel Children Hospital, Jalaram Road, Karelibagh, Vadodara, Gujarat 390018", "phone":"0265 246 2404", "city":"Vadodara"},
    {"name":"Dev Medical Store", "address":"852X+PRC, Pratap Rd, Opp. Hero Honda Showroom, Raopura, Jambubet, Vadodara, Gujarat 390001", "phone":"0265 243 8441", "city":"Vadodara"},

    {"name":"Yamuna Medical", "address":"7QWW+MCG, motitaki chowk, Rajkot, Gujarat 360001", "phone":"0281 244 8890" , "city":"Rajkot"},
    {"name":"Dharti Medical Agency", "address":"8, Vidya Nagar Main Rd, Manhar Plot Corner,Opposite Yash Hoapital, Manhar Plot, Bhakti Nagar, Rajkot, Gujarat 360002", "phone":"0281 248 3608" , "city":"Rajkot"},
    {"name":"Dev Pushp Medical Store", "address":"5 - 6, Saket Plaza, Hanuman Madhi Chowk, Raiya Rd, Rajkot, Gujarat 360005", "phone":"..." , "city":"Rajkot"},
    {"name":"Vikas Medical Store", "address":"Sardar Nagar Main Rd, Astron Chowk, Sardarnagar, Rajkot, Gujarat 360001", "phone":"089800 06424" , "city":"Rajkot"},
    {"name":"Jitesh Medical Store", "address":"Murlidhar Chambers, Kuvadava Rd, Opp. Ranchhoddas Ji Ashram, Bhagvati Park, Patel Nagar, Arya Nagar, Rajkot, Gujarat 360003", "phone":"0281 270 5518" , "city":"Rajkot"},
    {"name":"Murlidhar medical store", "address":"Kothariya Main Rd, nr. nilkanth cinema, Mehul Nagar, Jangleshwar, Rajkot, Gujarat 360001", "phone":"063525 45128" , "city":"Rajkot"},
    {"name":"Ashirwad Medical Centre", "address":"Shop no 3, 25, New Jagnath Rd, New Jagnath, Jagnath Plot, Rajkot, Gujarat 360001", "phone":"098242 21287" , "city":"Rajkot"},
    {"name":"Goplani Medicine", "address":"4, Suraj Apartment, Junction Plot Main Rd, Opp.Nagrik Bank, Junction Plot, Rajkot, Gujarat 360001", "phone":"0281 244 3161" , "city":"Rajkot"},
    {"name":"Gayatri Medical Centre", "address":"Sanjivani Complex, Vidya Nagar Main Rd, Vidya Nagar, Rajkot, Gujarat 360001", "phone":"0281 246 3469" , "city":"Rajkot"},
    {"name":"Hope Medical Store", "address":"Gujarat Housing Board, Kotecha Nagar, Rajkot, Gujarat 360001", "phone":"0281 245 2009" , "city":"Rajkot"},

    {"name":"New Diamond Medical", "address":"G1,Vardhman Arize, Kalubha Rd, near Suchak Hospital, Bhavnagar, Gujarat 364002", "phone":"093270 08757", "city":"Bhavnagar"},
    {"name":"Comred Medical Store", "address":"Akar Complex, Jail Rd, opposite Sir T Hospital, Near Dholakia, Devbagh, Bhavnagar, Gujarat 364001", "phone":"0278 243 1643", "city":"Bhavnagar"},
    {"name":"Hiren Medical Store", "address":"Shop No-lgf/3,Surydeep Complex, Kalanala, Bhavnagar, Gujarat 364001", "phone":"098989 25384", "city":"Bhavnagar"},
    {"name":"Apex Medical Store", "address":"G/10, Ayush Plaza, Jail Rd, near BIMS Hospital, Bhavnagar, Gujarat 364002", "phone":"083477 97201", "city":"Bhavnagar"},
    {"name":"Pujak Medical", "address":"847 A/1, Diamond Chowk, Mahila College Area, Deri Road Area, Tilak Nagar, Bhavnagar, Gujarat 364001", "phone":"....", "city":"Bhavnagar"},
    {"name":"Navjeevan Medical Center", "address":"3 Ayush Plaza, opp. Sir T Hospital, Bhavnagar, Gujarat 364001", "phone":"099784 40450", "city":"Bhavnagar"},
    {"name":"Medcare Medicines", "address":"Shop No 2, Thirthraj Complex, Kalubha Rd, Bhavnagar, Gujarat 364001", "phone":"095375 06506", "city":"Bhavnagar"},
    {"name":"Brahmani medical", "address":"Jail Rd, Devbagh, Bhavnagar, Gujarat 364001", "phone":"0278 300 4858", "city":"Bhavnagar"},
    {"name":"Genmed Medical", "address":"5,shivoday residency, Ghogha Cir, Ambawadi, Bhavnagar, Gujarat 364001", "phone":"....", "city":"Bhavnagar"},
    {"name":"Shree Hanumant Medical Store", "address":"Jai Jhulelal Chowk, Asht Vinayak Complex, Waghawadi Rd., Bhavnagar, Gujarat 364002", "phone":"075670 14888", "city":"Bhavnagar"},

    {"name":"Shreenathji Medical & Agency", "address":"Shop No 1,50,51,52 Mayur Complex, Main Road, Khodiyar Colony, Jamnagar, Gujarat 361006", "phone":"096624 33963", "city":"Jamnagar"},
    {"name":"Sanjeevani Medical Stores", "address":"21, Divyam complex, Main Road, Aerodrome Rd, Khodiyar Colony, Jamnagar, Gujarat 361006", "phone":"....", "city":"Jamnagar"},
    {"name":"Heera Medical", "address":"F3CC+Q92, Maheswari Nagar, Kadiawad, Jamnagar, Gujarat 361001", "phone":"085309 89898", "city":"Jamnagar"},
    {"name":"Jamnagar Medical", "address":"C3M8+2H5, Green City, Jamnagar, Gujarat 361005", "phone":"....", "city":"Jamnagar"},
    {"name":"Kotak Medical Store", "address":"Nr Subhas Brig, Nagnath Gate, Jamnagar, Gujarat 361001", "phone":"....", "city":"Jamnagar"},
    {"name":"Shreeji Medical", "address":"Road No 1 & Street No 3 , Galeria Complex&nbsp;, Patel Colony, Jamnagar, Gujarat 361008", "phone":"0288 275 3291", "city":"Jamnagar"},
    {"name":"Bhagyoday Medical Stores", "address":"Shop No.3-b\B, Avantika Complex, Gurudwara Rd, opp. Cricket Ground, Jamnagar, Gujarat 361001", "phone":"0288 255 9509", "city":"Jamnagar"},
    {"name":"Navtan Medical", "address":"1 Sidhivinayak Plaza, MIG Colony Corner, S T Road, Gujarat 361001", "phone":"....", "city":"Jamnagar"},
    {"name":"Vikas Medical", "address":"F3M4+XFW, Patel Colony Street-Sheri Number 9, Patel Colony, Jamnagar, Gujarat 361008", "phone":"0288 275 5715", "city":"Jamnagar"},
    {"name":"New Patel Medical", "address":"325/B VISHAL CHOWK, GIDC Phase-2, Jamnagar, Gujarat 361005","phone":"098988 68388","city":"Jamnagar"},

    {"name":"Gandhinagar Medical Store", "address":"B-3, Civil Hospital Compound, Sector 12B, Gandhinagar, Gujarat 382012", "phone":"098245 09656", "city":"Gandhinagar"},
    {"name":"Sun Medical & Pro. Store - Medical Store", "address":"opp. Shree Bhuvneshwar Mahadev Mandir, Sector - 6/C, Sector 6, Gandhinagar, Gujarat 382006", "phone":"094995 56756", "city":"Gandhinagar"},
    {"name":"Generic Medical Store", "address":"No.G-2, Sector 12B, 12, GH Rd, Sector 16, Gandhinagar, Gujarat 382016", "phone":"....", "city":"Gandhinagar"},
    {"name":"Venus Pharmacy", "address":"B-74,GF,PRAMUKH ARCADE NE.MIDDLE TOWN HOTEL, Kudasan, Gandhinagar, Gujarat 382421", "phone":"097144 62766", "city":"Gandhinagar"},
    {"name":"Mangalam Medical Store", "address":"Plot No. 445, G-5, GH Rd, Sector 16, Gandhinagar, Gujarat 382016", "phone":"098796 13121", "city":"Gandhinagar"},
    {"name":"Gita Medical Stores", "address":"6MM5+5CH, Nr. Dr. Raman Patel's Hospital, Sector 22, Gandhinagar, Gujarat 382021", "phone":"....", "city":"Gandhinagar"},
    {"name":"Manohar Medical Stores", "address":"Shopping Center, GH Rd, near Suvidha, Sector 17, Gandhinagar, Gujarat 382017", "phone":"079 2322 2975", "city":"Gandhinagar"},
    {"name":"Anand Medical Stores", "address":"6J5P+GPJ, GH Rd, Near GH-2 Circle, Sector 7/B, Sector 7, Gandhinagar, Gujarat 380007", "phone":"079 2324 7124", "city":"Gandhinagar"},
    {"name":"Dhruv Medical", "address":"6J8P+7Q4, Sector 6, Gandhinagar, Gujarat 982010", "phone":"094284 75065", "city":"Gandhinagar"},
    {"name":"Arti Medical Stores", "address":"Main Shopping Centre, Suvidha Sector 6 Office, G Rd, Sector 6-b, Gandhinagar, Gujarat 382006", "phone":"099241 15745", "city":"Gandhinagar"},

    {"name":"Health Care Medical Store", "address":"HX75+G4H, 100 Feet Rd, Yogi Swami Society, Vallabh Vidyanagar, Anand, Gujarat 388120", "phone":"097256 68735", "city":"Anand"},
    {"name":"Anand Medical Centre", "address":"Haridaya Building, opp. Laxmi Cinema, Anand, Gujarat 388001", "phone":"074005 74006", "city":"Anand"},
    {"name":"Vikram Medical Stores", "address":"HX46+9WJ, Navliwala Building, Railway Station Rd, Anand, Gujarat 388001", "phone":"02692 268 098", "city":"Anand"},
    {"name":"Pooja Medical", "address":"G 10 Bajkhedawala Complex, Nana Bazaar, Anand, Gujarat 388001", "phone":"098242 32113", "city":"Anand"},
    {"name":"Shraddha Hospital in Anand", "address":"Mahavir Rd, near Pioneer High School, Patel Colony, Sardar Ganj, Anand, Gujarat 388001", "phone":"098252 45108", "city":"Anand"},
    {"name":"Vrunda Medical store", "address":"Juna Rasta, OPP.SHREEMAN, Ganesh Chokdi, Sardar Ganj, Anand, Gujarat 388001", "phone":"093774 69468", "city":"Anand"},
    {"name":"Ishwarkrupa medical store", "address":"Ahinsha Chowk, behind charotar bank, near Arpan Hospital, Sardar Ganj, Anand, Gujarat 388001", "phone":"092271 36268", "city":"Anand"},
    {"name":"Santram Medical Store", "address":"HX47+W5J, Mayfair Road, Gamdi Vad, Sardar Ganj, Anand, Gujarat 388001", "phone":"....", "city":"Anand"},
    {"name":"Parag Medical", "address":"HX44+XP3, Near Sunrise Plywood Store, Ganesh Colony, Anand, Gujarat 388001", "phone":"098791 83372", "city":"Anand"},
    {"name":"Afiya Medical Store", "address":"GWXG+CJP, Town Hall Rd, Mota Bazaar, Vallabh Vidyanagar, Anand, Gujarat 388120", "phone":"02692 231 246", "city":"Anand"},

    {"name":"Nadiad Medical Store", "address":"Bhagol, Dabhan, Station Rd, Nadiad, Gujarat 387001", "phone":"090169 44201", "city":"Nadiad"},
    {"name":"New Ambika Medical Store", "address":"MVR7+J8Q, Nadiad, Dumral Bazar, Yogiraj Society, Nadiad, Gujarat 378001", "phone":"070164 52097", "city":"Nadiad"},
    {"name":"Milan Medical Store", "address":" MVR7+FQG, near santram mandir, opp fire brigade, Globe Cinema Rd, Nadiad, Gujarat 387001", "phone":"0268 256 2061", "city":"Nadiad"},
    {"name":"Naman Medical Store", "address":"Santram Road, Nadiad, Gujarat 387001", "phone":"097378 89222", "city":"Nadiad"},
    {"name":"Krishna Medical Stores", "address":"MVR7+J3C, DP Desai Rd, Junaraopura, Nadiad, Gujarat 387001", "phone":"096384 82332", "city":"Nadiad"},
    {"name":"J.K. Medical Store", "address":"MVV6+82F, Bus Station Road, Nadiad, Gujarat 387001", "phone":"085111 33152", "city":"Nadiad"},
    {"name":"Paras HealthCare", "address":"Santram Mandir Rd, near Yamuna Farsan Mart, Shanti Nagar, Nadiad, Gujarat 387001", "phone":"088662 05999", "city":"Nadiad"},
    {"name":"Ambica Medical Store", "address":"C.P Chambers, Bus -Station, Santram Mandir Rd, opposite Sanjay Sales New, Shanti Nagar, Nadiad, Gujarat 387001", "phone":"070164 52097", "city":"Nadiad"},
    {"name":"Pramukh Medical Store", "address":"SH 61, Shanti Nagar, Nadiad, Gujarat 387001", "phone":"099094 29295", "city":"Nadiad"},
    {"name":"Kishan Medical Stores", "address":"Patel bakery road MVP6+PHP l g marg, near vaishali Cineplex, Nadiad, Gujarat 387002", "phone":"070435 37220", "city":"Nadiad"},

    {"name": "Chandan Medical","address": "6MRF+32V, Lotus Colony, Madhapar, Bhuj, Gujarat 370001","phone":"02832 224 284","city":"Bhuj"},
    {"name": "Super medical","address": "Bharatnagar chokdi, near mukhtar pan centre, Sanjog Nagar, Bhuj, Gujarat 370001","phone":"096383 84555","city":"Bhuj"},
    {"name": "Bhuj Medical Store","address": "6MX9+XR9, Old Dhatia Falia, Bhuj, Gujarat 370001","phone":"....","city":"Bhuj"},
    {"name": "Shree Siddihnath Medical Store","address": "Hospital Road Rajaram Complex, Bhuj, Gujarat 370001","phone":"094298 96613","city":"Bhuj"},
    {"name": "Bhoomi Medical Store","address": "Banker's Colony, Bhuj, Gujarat 370001","phone":"02832 256 760","city":"Bhuj"},
    {"name": "Pratham Medical","address": "Nr Santoshi Mata Mandir V D Road, Bhuj, Gujarat 370001","phone":"099788 27604","city":"Bhuj"},
    {"name": "Kutch Medical","address": "6MWF+3C9, Hospital Rd, Vijay Nagar, Bhuj, Gujarat 370001","phone":"....","city":"Bhuj"},
    {"name":"Shalibhadra Medical","address":"Vijay Nagar, 201, Hospital Rd, Vijay Nagar, Bhuj, Gujarat 370001","phone":"....","city":"Bhuj"},
    {"name":"Maa Medical store","address":"49,LOTUS COLONY STREET NO 2, CHANDAN MEDICAL STTREET , OPP .PATEL, Eye Hospital Rd, Bhuj, Gujarat 370001","phone":"....","city":"Bhuj"},
    {"name":"Balaji medical","address":"Gandhi circle road, opp. bank of baroda, Madhapar, Gujarat 370001","phone":"....","city":"Bhuj"},
]

@app.route('/')
def hospital():
    return render_template('hospital.html')

@app.route('/search', methods=['POST'])
def search_hospital_stores():
    city = request.form['city'].title()
    # Filter the results by city
    hospital = [store for store in hospital_data if store['city'] == city]
    lab = [store for store in lab_data if store['city'] == city]
    medical = [store for store in medical_data if store['city'] == city]
    
    # Sort the results by store name
    hospital_result = sorted(hospital, key=lambda x: x['name'])
    lab_result = sorted(lab, key=lambda x: x['name'])
    medical_result = sorted(medical , key=lambda x: x['name'])

    return render_template('hospital.html', city=city, hospital_display=hospital_result,lab_display=lab_result,medical_display=medical_result)

# if __name__ == '__main__':
#     app.run(debug=True)

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))  # use the port given by Render
    app.run(host='0.0.0.0', port=port)